### ISSUE TITLE
invalid syntax when installation of ROTLA

### ISSUE THREAD

**Issue by Pilibeibei** [NIEHS/ROTLA#1]
Hi, I have issue when installing the ROTLA on Ubuntu20.04VM. I have installed blat and add it to the path in the "paths.cfg" as following:
/home/abc/blatSrc
blat = blat

Then I run "sudo python2 setup.py install" and received the error as invalid syntax, below are the results. 
running install
running bdist_egg
running egg_info
writing requirements to ROTLA.egg-info/requires.txt
writing ROTLA.egg-info/PKG-INFO
writing top-level names to ROTLA.egg-info/top_level.txt
writing dependency_links to ROTLA.egg-info/dependency_links.txt
writing entry points to ROTLA.egg-info/entry_points.txt
reading manifest file 'ROTLA.egg-info/SOURCES.txt'
writing manifest file 'ROTLA.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ROTLA
copying build/lib.linux-x86_64-2.7/ROTLA/__init__.py -> build/bdist.linux-x86_64/egg/ROTLA
copying build/lib.linux-x86_64-2.7/ROTLA/ROTLA.py -> build/bdist.linux-x86_64/egg/ROTLA
copying build/lib.linux-x86_64-2.7/ROTLA/aligned_bases_from_psl.py -> build/bdist.linux-x86_64/egg/ROTLA
copying build/lib.linux-x86_64-2.7/ROTLA/cli.py -> build/bdist.linux-x86_64/egg/ROTLA
copying build/lib.linux-x86_64-2.7/ROTLA/compile_breakpoint_results.py -> build/bdist.linux-x86_64/egg/ROTLA
byte-compiling build/bdist.linux-x86_64/egg/ROTLA/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/ROTLA/ROTLA.py to ROTLA.pyc
byte-compiling build/bdist.linux-x86_64/egg/ROTLA/aligned_bases_from_psl.py to aligned_bases_from_psl.pyc
byte-compiling build/bdist.linux-x86_64/egg/ROTLA/cli.py to cli.pyc
byte-compiling build/bdist.linux-x86_64/egg/ROTLA/compile_breakpoint_results.py to compile_breakpoint_results.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/config
copying paths.cfg -> build/bdist.linux-x86_64/egg/config
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ROTLA.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ROTLA.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ROTLA.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ROTLA.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ROTLA.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ROTLA.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ROTLA.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/ROTLA-0.1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ROTLA-0.1.0-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/ROTLA-0.1.0-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/ROTLA-0.1.0-py2.7.egg
Extracting ROTLA-0.1.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
ROTLA 0.1.0 is already the active version in easy-install.pth
Installing ROTLA script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/ROTLA-0.1.0-py2.7.egg
Processing dependencies for ROTLA==0.1.0
Searching for Click>=6.0
Reading https://pypi.org/simple/Click/
Downloading https://files.pythonhosted.org/packages/60/e2/9c9b456c0ddaa1268f320bc2f739f1598290f5cf3acf8d65e2c36fde8afe/click-8.0.0a1.tar.gz#sha256=e4315a188403c0258bbc4a4e31863e48fc301c4e95b8007a8eeda0391158df13
Best match: click 8.0.0a1
Processing click-8.0.0a1.tar.gz
Writing /tmp/easy_install-84T0Yf/click-8.0.0a1/setup.cfg
Running click-8.0.0a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-84T0Yf/click-8.0.0a1/egg-dist-tmp-cERIyn
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    data_files=[('config', ['paths.cfg'])],
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 449, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 691, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 738, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 783, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 710, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 736, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 921, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1189, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1175, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-84T0Yf/click-8.0.0a1/setup.py", line 3, in <module>
    
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 349, in _parse_attr
    module = import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/easy_install-84T0Yf/click-8.0.0a1/src/click/__init__.py", line 7, in <module>
  File "/tmp/easy_install-84T0Yf/click-8.0.0a1/src/click/core.py", line 91
    f"{hint}. Command {base_command.name!r} is set to chain and"
                                                               ^
SyntaxError: invalid syntax

**Comment by burkholderab** [comment]
It looks like this issue is due to an attempt to install and import a version of the Click package that is not compatible with python 2.7. I've updated the setup.py script to require Click >=6.0 and <= 7.1.12. Try downloading a fresh copy and running the install script again.

**Comment by Pilibeibei** [comment]
Thanks for the quick reply. I have successfully installed. However when run the code I have an error called "ConfigParser.MissingSectionHeaderError: File contains no section headers." see below details.

Traceback (most recent call last):
  File "/usr/local/bin/ROTLA", line 11, in <module>
    load_entry_point('ROTLA==0.1.0', 'console_scripts', 'ROTLA')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jing/.local/lib/python2.7/site-packages/ROTLA-0.1.0-py2.7.egg/ROTLA/__init__.py", line 15, in <module>
    os.path.dirname(os.path.abspath(__file__)), '../config', 'paths.cfg'))
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/jing/.local/lib/python2.7/site-packages/ROTLA-0.1.0-py2.7.egg/ROTLA/../config/paths.cfg, line: 1
'/home/jing/bin/x86_64/\n'

**Comment by burkholderab** [comment]
This looks like an issue with the contents of paths.cfg. Make sure it looks similar to the example below and includes the header line in square brackets and the full path to your blat executable:

[paths]
blat = /home/abc/blatSrc/blat

Note that the installer places paths.cfg in ~/.local/lib/python2.7/site-packages/ROTLA-0.1.0-py2.7.egg/config/. You can either edit the file there, or edit the copy in the ROTLA source folder and re-run the setup script.
